[package]
name = "rt"
version = "0.1.0"
authors = ["ishbosamiya <ishbosamiya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.11.0"
rand = "0.8.3"
crossbeam-channel = "0.5"

[dev-dependencies]
criterion = { version = "0.3.4", features = ["html_reports"]}

[[bench]]
name = "ray_collision_bench"
harness = false

[profile.bench]
debug = true

[profile.release]
debug = true